resources:
  - type: storage.v1.bucket
    name: sls-pagseg-checkout-dev-1514894169495
  - type: cloudfunctions.v1beta2.function
    name: pagseg-checkout-dev-first
    properties:
      location: us-central1
      availableMemoryMb: 256
      timeout: 60s
      function: getPagSeg
      sourceArchiveUrl: >-
        gs://sls-pagseg-checkout-dev-1514894169495/serverless/pagseg-checkout/dev/1514894179354-2018-01-02T11:56:19.354Z/pagseg-checkout.zip
      httpsTrigger:
        url: path
